### ISSUE TITLE
Tabs > spaces 

### ISSUE THREAD

**Issue by BradHarris** [MappedIn/styleguide#1]
> Indent with 2 spaces

> This is easy to setup in Sublime, for instance, by changing the Indentation in the bottom right corner. Check Indent using spaces and Tab width: 2.

> This is to provide readibility as levels of indentation grow.

Indent with tabs

This is easy to setup in Sublime, for instance, by changing the Indentation in the bottom right corner. Check Indent using tabs and Tab width: 2.

This is to provide readability as levels of indentation grow.

**Comment by BradHarris** [comment]
let the flame war begin

**Comment by ppaskaris** [comment]
![image](https://cloud.githubusercontent.com/assets/509992/18643214/155678ca-7e72-11e6-83a2-751421c5c674.png)

**Comment by axiomaticdesign** [comment]
I think @ppaskaris' point that spaces ensures transfer-ability with no downsides pretty much wins.

**Comment by BradHarris** [comment]
Transfer-ability to what exactly?

**Comment by axiomaticdesign** [comment]
Pasting between editors, browsers, input fields, slack, etc...

**Comment by BradHarris** [comment]
That's a really soft downside compared to the readability you get in your IDE with tabs. Plus the number of places that you would be pasting code that wouldn't format nicely has to be close to 0.

**Comment by axiomaticdesign** [comment]
I paste code into GitHub and slack all the time. You can configure your IDE to display spaces better too.

**Comment by BradHarris** [comment]
can you configure sublime to show 2 spaces as 4 spaces?

**Comment by ppaskaris** [comment]
[yes](https://www.sublimetext.com/docs/3/indentation.html)

**Comment by BradHarris** [comment]
Yeah, I can't figure out how to make sublime do that. Maybe there is a plugin to make it happen though.

**Comment by ppaskaris** [comment]
I'm OK with tabs so long they are used strictly for indentation and not alignment, and that we don't try to align things with spaces (which would cause them to become mixed).

**Comment by axiomaticdesign** [comment]
I will add in a bit that says to only align with tabs, not tabs and spaces. Seems like 2 spaces has won the war.

**Comment by ppaskaris** [comment]
I meant that we should not try to align code whatsoever.

**Comment by BradHarris** [comment]
I still don't like 2 spaces over tabs. But we should probably decide at some point. I say we put it to a vote.

**Comment by PaulBernhardt** [comment]
http://www.strawpoll.me/11271361
