### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by axiomaticdesign** [MappedIn/styleguide#2]
Is there a fancy thing to generate it?

@BradHarris @ppaskaris

**Comment by ppaskaris** [comment]
I'm sure there's a tool somewhere that does it. I used to use [Marked](http://marked2app.com/) when I had a MacBook.

**Comment by PaulBernhardt** [comment]
If you use atom there is this: https://atom.io/packages/markdown-toc

Paul Bernhardt | Developer Evangelist

paul@mappedin.com | www.mappedin.com[image:
https://ssl.gstatic.com/ui/v1/icons/mail/images/cleardot.gif]
<http://www.mappedin.com/>
