### ISSUE TITLE
Citation Needed

### ISSUE THREAD

**Issue by a1gemmel** [MappedIn/styleguide#7]
>For Loops
>
>Define the length of the iteration in the initial declaration, to prevent creating it on every loop.
>
>for (let i = 0, iLen = collection.length; i < iLen; ++i) {
>  // good
>}
>
>for (let i = 0; i < collection.length; ++i) {
>  // bad
>}
>This saves more time the bigger the collection is. For small collections, the amount of milliseconds saved is negligible, but it is recommended to use this method as a best practice.

Google suggests that this is an antiquated practice and there is no performance difference in browsers newer than IE9.

**Comment by axiomaticdesign** [comment]
I cite @ppaskaris. But also the intention is the improvement is seen on larger data sets.

**Comment by ppaskaris** [comment]
It doesn't seem to be valid anymore according to micro-benchmarks. I don't know if I'll bother trying to break the habit.
